name: CI de Python con Cobertura de Codecov (Proyecto A)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependencias y ejecutar tests (Proyecto A)
      run: |
        cd proyecto_a
        pip install -r requirements.txt
        # Ejecuta pytest y genera el informe XML en la raíz del workspace de GitHub Actions
        pytest --cov=. --cov-report=xml --junitxml=./test-results-a.xml

    - name: Subir informe de cobertura a Codecov
      uses: codecov/codecov-action@v4
      with:
        # La ruta al archivo coverage.xml generado por pytest en el paso anterior
        files: ./proyecto_a/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }} # Token de Codecov, debe ser un secreto en GitHub
        fail_ci_if_error: true # Opcional: falla la CI si la subida de Codecov falla
        verbose: true # Opcional: muestra logs detallados
